name: Docker Build

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "backend/**"
      - "deployment/**"
      - ".github/workflows/docker-build.yml"

permissions:
  contents: read

jobs:
  build:
    name: Build backend image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build --tag s201-backend:test backend
